rabbitmq/rabbitmq-stream-go-client

- pkg/stream/client.go
- pkg/stream/client_test.go
- pkg/stream/coordinator.go
- pkg/stream/coordinator_test.go
> Add Test client

- examples/batch/batch_publish.go
- examples/getting_started.go
- perfTest/perftest.go
- pkg/stream/buffer_reader.go
- pkg/stream/client.go
- pkg/stream/coordinator.go
- pkg/stream/producer.go
- pkg/stream/response.go
> Refactor sockets

- .github/workflows/test_and_publish_image.yml
- Makefile
- README.md
- VERSION
- comopose/docker-compose.yml
- examples/getting_started.go
- examples/publishersError/publisherError.go
- perfTest/cmd/silent.go
- pkg/stream/brokers.go
- pkg/stream/client.go
- pkg/stream/constants.go
- pkg/stream/consumer_test.go
- pkg/stream/coordinator.go
- pkg/stream/coordinator_test.go
- pkg/stream/enviroment.go
- pkg/stream/enviroment_test.go
- pkg/stream/producer.go
- pkg/stream/producer_test.go
- pkg/stream/server_frame.go
- pkg/stream/stream_options.go
- pkg/system_integration/integration_test.go
- change the port to 5552
- Handle the publish error
> Change the port to 5552

- pkg/ha/ha_publisher.go
- pkg/stream/client.go
- pkg/stream/constants.go
- pkg/stream/server_frame.go
paired with @MarcialRosales .  
thanks a lot for the help !
> Add CRC command

- examples/getting_started.go
- examples/offsetTracking/offsetTracking.go
- pkg/stream/client.go
- pkg/stream/server_frame.go
fixes https://github.com/rabbitmq/rabbitmq-stream-go-client/issues/25
> Implement keepalive

- pkg/stream/client.go
- pkg/stream/dialer_posix.go
- pkg/stream/dialer_windows.go
> Fix for file descriptor type difference on Windows

- README.md
- pkg/stream/client.go
- pkg/stream/constants.go
- pkg/stream/producer.go
- pkg/stream/producer_test.go
closed https://github.com/rabbitmq/rabbitmq-stream-go-client/issues/64
> Add batchPublishingDelay

- pkg/amqp/types.go
- pkg/stream/consumer_test.go
closes https://github.com/rabbitmq/rabbitmq-stream-go-client/issues/66
> Add messages properites

- README.md
- examples/README.md
- examples/automaticOffsetTracking/automaticOffsetTracking.go
- pkg/stream/client.go
- pkg/stream/consumer.go
- pkg/stream/consumer_test.go
- pkg/stream/coordinator.go
- pkg/stream/enviroment_test.go
- pkg/stream/server_frame.go
Fixes https://github.com/rabbitmq/rabbitmq-stream-go-client/issues/102
> Auto track offest

- pkg/amqp/types.go
- pkg/message/interface.go
- pkg/stream/consumer_test.go
- pkg/stream/producer.go
> Add details on message confirmation

- pkg/stream/constants.go
Same problem found here: https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/issues/41
> Handle the loopback error

- pkg/amqp/types.go
- pkg/message/interface.go
- pkg/stream/consumer_test.go
Fixes: https://github.com/rabbitmq/rabbitmq-stream-go-client/issues/128
> Remove message visibility

- pkg/stream/client.go
- pkg/stream/consumer.go
- pkg/stream/server_frame.go
Signed-off-by: Gabriele Santomaggio <G.santomaggio@gmail.com>
ref https://groups.google.com/g/rabbitmq-users/c/0zldgRJIA-Y
> Configure initial credits

- README.md
- pkg/stream/client.go
- pkg/stream/client_test.go
- pkg/stream/constants.go
- pkg/stream/environment.go
- pkg/stream/server_frame.go
- pkg/stream/stream_stats.go
Closes: https://github.com/rabbitmq/rabbitmq-stream-go-client/issues/190
> Implement stream stats

- examples/tail/stream_tail.go
> stream tail example

- pkg/stream/environment.go
- pkg/stream/environment_test.go
- pkg/stream/locator.go
- pkg/stream/test_helpers.go
Closes #231 
QueryOffset gets the last consumer offset stored for a consumer and stream name
> QueryOffset

- Makefile
- compose/ha_tls/docker-compose.yml
- compose/tls/conf/enabled_plugins
update make file with the new docker image expose the ports to the docker compose
> change the docker image

- generate/generate_amqp10_messages.go
Create output directory when saving.
Output deterministic message while not using 'map'.
This is mainly for unit test in [https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/pull/367](https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/pull/367)
But I am not sure whether this script is being used in this repo too?
> Add UUID type in generated message.

- README.md
- examples/README.md
- examples/single_active_consumer/README.md
- examples/single_active_consumer/producer.go
- examples/single_active_consumer/single_active_consumer.go
- pkg/stream/available_features.go
- pkg/stream/buffer_writer.go
- pkg/stream/client.go
- pkg/stream/constants.go
- pkg/stream/consumer.go
- pkg/stream/consumer_sac_test.go
- pkg/stream/coordinator.go
- pkg/stream/filtering_test.go
- pkg/stream/server_frame.go
- pkg/stream/utils.go
Implement the Single-Active Consumer Feature https://www.rabbitmq.com/blog/2022/07/05/rabbitmq-3-11-feature-preview-single-active-consumer-for-streams
> Implement Single Active Consumer

- pkg/stream/buffer_writer.go
- pkg/stream/client.go
- pkg/stream/client_super_stream_test.go
- pkg/stream/constants.go
- pkg/stream/server_frame.go
The first part for the super-stream feature. Create and delete super-stream
> Create super stream / delete super stream 

- .github/workflows/build_and_test.yml
- pkg/stream/super_stream_consumer.go
- pkg/stream/super_stream_consumer_test.go
- pkg/stream/super_stream_producer.go
Closes https://github.com/rabbitmq/rabbitmq-stream-go-client/issues/299
> Filtering for super stream

- .gitignore
- pkg/stream/coordinator.go
for last_stored_offset
fixes:https://github.com/rabbitmq/rabbitmq-stream-go-client/issues/306
> change the default value for last_stored_offset

- pkg/stream/server_frame.go
Ref https://github.com/rabbitmq/rabbitmq-stream-go-client/discussions/318 
Improve the logs messages in case the consumer is closed during the dispatch
> improve the message log

- README.md
- examples/offsetTracking/offsetTracking.go
- examples/single_active_consumer/single_active_consumer.go
- pkg/stream/super_stream_consumer.go
Fixes: https://github.com/rabbitmq/rabbitmq-stream-go-client/issues/322
> Add manual commit for super stream consumet

- pkg/ha/ha_publisher.go
- pkg/ha/ha_publisher_test.go
Discussed here: https://github.com/rabbitmq/rabbitmq-stream-go-client/issues/332
> Add BatchSend to HA Producer

- pkg/stream/environment.go
> fix new producer log

- pkg/stream/consumer_test.go
Test related to #412, to avoid similar regressions.
> Test to ensure no chunks are skipped in slow consumers
