Makefile, examples/getting_started.go, examples/offset/offset.go, examples/publishersError/publisherError.go, perfTest/cmd/commands.go, perfTest/cmd/silent.go, pkg/stream/client.go, pkg/stream/client_test.go, pkg/stream/constants.go, pkg/stream/consumer.go, pkg/stream/consumer_test.go, pkg/stream/coordinator.go, pkg/stream/enviroment.go, pkg/stream/enviroment_debug.go, pkg/stream/enviroment_test.go, pkg/stream/listeners.go, pkg/stream/producer.go, pkg/stream/producer_test.go, pkg/stream/server_frame.go, pkg/stream/socket.go, pkg/stream/utils.go, pkg/stream/utils_test.go
https://github.com/rabbitmq/rabbitmq-server/pull/3060
fix offest client side and test
=> Send advertised host and port in open

examples/getting_started.go, examples/offset/offset.go, examples/offsetTracking/offsetTracking.go, examples/publishersError/publisherError.go, pkg/ha/ha_publisher.go, pkg/stream/client.go, pkg/stream/client_test.go, pkg/stream/consumer_test.go, pkg/stream/coordinator.go, pkg/stream/enviroment.go, pkg/stream/enviroment_debug.go, pkg/stream/enviroment_test.go, pkg/stream/producer.go, pkg/stream/producer_test.go, pkg/stream/server_frame.go, pkg/stream/stream_suite_test.go
reduce the scope of the mutex. Optimize producer/consumer closing in case of
remove stream.
=> refactor the coordinator

.github/workflows/codeql-analysis.yml, Makefile, README.md, VERSION, examples/getting_started.go, examples/haProducer/http/http.go, examples/haProducer/producer.go, examples/offsetStart/offset.go, examples/offsetTracking/offsetTracking.go, examples/publishersError/publisherError.go, examples/tls/getting_started_tls.go, perfTest/cmd/silent.go, pkg/ha/ha_publisher.go, pkg/stream/client.go, pkg/stream/client_test.go, pkg/stream/constants.go, pkg/stream/consumer_test.go, pkg/stream/coordinator.go, pkg/stream/coordinator_test.go, pkg/stream/enviroment.go, pkg/stream/enviroment_test.go, pkg/stream/producer.go, pkg/stream/producer_test.go, pkg/stream/server_frame.go, pkg/system_integration/integration_test.go
add smart publish to aggregate the messages.
- add batch size parameter on publish side 
- add queue size parameter on publish side
closes https://github.com/rabbitmq/rabbitmq-stream-go-client/issues/52
pair with @MarcialRosales
=> add smart publish to

.gitignore, perfTest/cmd/silent.go, perfTest/cmd/version.go, perfTest/perftest.go
This addresses https://github.com/rabbitmq/rabbitmq-stream-go-client/issues/71.
While working on this, I realised a few things:
- The `PerfTest [command]` actually originates in cobra's default usage template, specifically here https://github.com/spf13/cobra/blob/4fd30b69ee2b62cf3bbecf0a423f8a1ee47f5f24/command.go#L493
- Rather than making a change in cobra, I think that the `silent` command should be the default one. The name always grated me, and now I know why: it doesn't say anything about what it does. WDYT @Gsantomaggio ?
By the way, I think that this CLI could learn a lot from https://clig.dev
=> Don't error on the default help command, or version

perfTest/cmd/commands.go, perfTest/cmd/silent.go, pkg/stream/brokers.go
Fixes https://github.com/rabbitmq/rabbitmq-stream-go-client/issues/74
=> Fixes https://github.com/rabbitmq/rabbitmq-stream-go-client/issues/74

pkg/stream/aggregation.go, pkg/stream/client.go, pkg/stream/constants.go, pkg/stream/consumer_test.go, pkg/stream/enviroment.go
leader is not ready yet, add also a small fix in the aggregation
fixes https://github.com/rabbitmq/rabbitmq-stream-go-client/issues/96
=> Return an error in the leader is not ready yet

README.md, pkg/stream/client_test.go, pkg/stream/enviroment.go
closes https://github.com/rabbitmq/rabbitmq-stream-go-client/issues/99
Create the stream idempotent way only if the parameters are the same.
`Precondition Failed` error is raised in In case the stream has different parameters 
use `env.StreamExists(streamName)` to check if the stream exists
=> Make stream creation idempotent

pkg/stream/coordinator.go, pkg/stream/enviroment_test.go, pkg/stream/producer.go, pkg/stream/producer_test.go
Fixes https://github.com/rabbitmq/rabbitmq-stream-go-client/issues/103
=> Wait For Inflight Messages

README.md, examples/getting_started.go, perfTest/cmd/commands.go, perfTest/cmd/silent.go, pkg/stream/consumer.go, pkg/stream/consumer_test.go, pkg/stream/server_frame.go
Add the perftest flag
Closes https://github.com/rabbitmq/rabbitmq-stream-go-client/issues/109
=> Add flag to configure the CRC

pkg/stream/client.go, pkg/stream/constants.go, pkg/stream/consumer.go, pkg/stream/consumer_test.go
When we susbcribe to a stream for the first time with a named consumer and with LastConsumed offset, we get the error "19 No Offset" from the broker. 
We should not throw the error but instead default lastOffset to 0.
=> Lastconsumed when no offset

README.md, pkg/stream/consumer.go, pkg/stream/consumer_test.go
Up until now we could only commit the last delivered message in case of manual offset tracking and automatically, after N messages or after N unit of time.
However, there are scenarios where we need to commit a given offset, not necessarily the very last delivered offset. This is specially necessary when we process messages in the background, outside of the message handler method.
=> Store custom offset

Makefile, go.mod, go.sum, pkg/stream/client_test.go, pkg/stream/consumer_test.go, pkg/stream/enviroment.go, pkg/stream/enviroment_test.go, pkg/stream/producer_test.go, pkg/stream/socket.go, pkg/stream/stream_suite_test.go, pkg/stream/types.go, pkg/stream/utils_test.go
- Refactor socket module
- Refactor stream module tests
- Update Makefile
- Update go routines in tests
The `socket` module was using `sync/atomic` and `sync/mutex`. Using both is not necessary, and atomic
package may give headaches to users in architectures other than amd64. This PR changes the module to use
only mutexes.
The Makefile is changed to permit starting RabbitMQ using different container technologies, like containerd
with `nerdctl` cli. Not everyone is happy to Docker's recent license change :-) It also uses ginkgo as test
runner. It allows to use the same flags as `go test` and it provides a more condensed output, perhaps easier
to read.
The before/after suite functions have been moved to the suite test file, where they belong :-)
=> Refactor stream package

go.sum, pkg/integration_test/integration_test_suite_test.go, pkg/integration_test/stream_integration_test.go, pkg/stream/client.go, pkg/stream/consumer.go, pkg/stream/consumer_test.go, pkg/stream/coordinator.go, pkg/stream/server_frame.go
Signed-off-by: Gabriele Santomaggio <G.santomaggio@gmail.com>
The  PR fixes the wrong offset stored.
It is in draft since tests are missing.
=> Fixes #158

.github/workflows/test_and_publish_image.yml, Makefile, pkg/stream/utils.go
Duration prints its value in nanoseconds. Earlier, we were printing: "timeout 10000000000 ms <...>", which is not correct. The default timeout is 10 seconds or 10,000 ms.
Start `nc` as follows:
```bash
nc -l localhost 5552
```
Run stream perf-test in a different terminal. Observe the error message after 10 seconds.
=> Fix timeout error log message

perfTest/cmd/commands.go, perfTest/cmd/silent.go
For small message sizes, the default initial credit value of 10 is too low, resulting in decreased consumer performance.
This exposes the initial credit configuration, so users can decide on what values works best for them.
The default is kept the same.
=> Add initial-credits flag to perfTest

pkg/stream/buffer_reader.go, pkg/stream/consumer_test.go
The `readUint8Array` function calls the `encoding/binary.Read` function with a `*[]uint8` slice. However, [that function](https://cs.opensource.google/go/go/+/refs/tags/go1.20.2:src/encoding/binary/binary.go;l=229) will fallback to using reflection on point to slice types, which is much slower. By using a `[]uint8` directly, performance increases drastically for large message sizes.
For 400 byte message, here's the results before the fix:
```
$ go run perftest.go --time 10 --consumer-offset next --fixed-body 400
2023/03/31 18:11:35 [info] - Silent (1.1.0) Simulation, url: [rabbitmq-stream://guest:guest@localhost:5552/%2f] publishers: 1 consumers: 1 streams: [perf-test-go]
2023/03/31 18:11:35 [info] - Declaring streams: [perf-test-go]
2023/03/31 18:11:35 [info] - stream perf-test-go, meta …
```
=> Fix consumer performance bottleneck

pkg/raw/client.go
Heartbeat frame is just a header frame. We were reading the header once,
and then reading 4 bytes again, during the handle of the hearbeat frame.
That was missaligning the buffer and causing a panic on next iteration.
=> Fix heartbeat frame handle

pkg/stream/environment.go, pkg/stream/environment_test.go, pkg/stream/locator.go
Closes #233
QueryPartitions returns a list of partition streams for a given superstream name.
=> QueryPartitions in Environment

pkg/stream/environment.go, pkg/stream/environment_test.go, pkg/stream/locator.go, pkg/stream/util.go
Closes #228
This PR adds QuerySequence to the public API for v2
- QuerySequence retreives the publsihingID for a given producer and stream name.
- The retry tests inherit the same flaky behaviour as QueryStreamStats
- QuerySequence returns a uint64 and an error. 
- Similar to stream stats loggin events occur if the selecte locator fails to initialize, or of the locator operation fails. 
Question for reviewers, should the public functions return a custom type to encapsulate data from the raw layer? (see QueryStreamStats where we have a stream.Stats type)
=> QuerySequence v2

.github/workflows/build_test_linux.yml, pkg/stream/stream_suite_test.go, pkg/stream/system_test.go
Skeleton for system tests. Add Ginkgo-style tests here. Assume RabbitMQ is running.
Important to include the build flag `rabbitmq.stream.system_test`
=> Skeleton for system tests

pkg/stream/stream_suite_test.go, pkg/stream/system_test.go
This test uses the public API of the stream package to do a lifecycle test or producing and consuming messages to a stream. 
Todo's
- Incorporate smart producer when it has been merged into v2
- Ensure the number of consumed messages matches the number of produced messages
=> Stream pkg sys test

examples/getting_started.go, pkg/stream/client.go, pkg/stream/consumer.go, pkg/stream/consumer_test.go, pkg/stream/coordinator.go, pkg/stream/server_frame.go
Expose some chunk information. For the moment, I'd start with `GetEntriesCount` which gives the number of entities for chunk.
=> Expose GetEntriesCount chunk information

pkg/stream/client.go, pkg/stream/client_test.go, pkg/stream/coordinator.go, pkg/stream/socket.go, pkg/stream/utils.go
Client.queryOffset/queryPublisherSequence/StreamStats were fixed to prevent deadlock in case of request timeout (for example rabbit server is down). Now these methods returns error immidiately if it occured and doesn't try to read from data chanel, because in case of request timeout it hangs (no other gorouitine would write to this channel).
Also Client is extended with additional field socketCallTimeout, for testing purposes (decrease running time of new tests).
Closes #273
=> pkg/client/stream: fix deadlock for client methods

Makefile, pkg/stream/available_features.go, pkg/stream/available_features_test.go, pkg/stream/client.go, pkg/stream/server_frame.go
=> Exchange version

pkg/stream/client.go, pkg/stream/consumer_test.go, pkg/stream/filtering_test.go, pkg/stream/producer.go
Add a control to avoid to create a filtering producer with subentry bach enabled
=> Avoid to create filtering producer with subentry batch

README.md, pkg/stream/stream_stats.go
The method name may be misleading. It does not indicate the last offset of the stream. It indicates the last uncommited chunk id. This information is not necessary. The user should use CommittedChunkId().
=> remove the LastOffset()

README.md, pkg/stream/super_stream_consumer.go, pkg/stream/super_stream_consumer_test.go
closes: https://github.com/rabbitmq/rabbitmq-stream-go-client/issues/303
=> add auto-commit to the super stream consumer

pkg/stream/client.go, pkg/stream/client_test.go, pkg/stream/coordinator_test.go, pkg/stream/environment.go, pkg/stream/environment_test.go
closes: https://github.com/rabbitmq/rabbitmq-stream-go-client/issues/312
=> Expose the RPC TImeout call

pkg/stream/environment.go, pkg/stream/environment_test.go
Fixes: https://github.com/rabbitmq/rabbitmq-stream-go-client/issues/309
=> Fix multi uris connection

pkg/stream/consumer.go
The method does not indicate the last message consumed of the stream but the last stored offset. The method was added to help the user, but it created confusion. `env.QueryOffset(consumerName, streamName)` should be used
ref: https://github.com/rabbitmq/rabbitmq-stream-go-client/issues/321
=> Deprecate LastConsumed method

pkg/stream/constants.go
Reduce `minBatchPublishingDelay` to 1ms instead of 50ms.
Discussion: https://github.com/rabbitmq/rabbitmq-stream-go-client/issues/332
=> Reduce `minBatchPublishingDelay` to 1ms

pkg/stream/client.go, pkg/stream/consumer_sac_test.go, pkg/stream/consumer_test.go, pkg/stream/coordinator.go, pkg/stream/server_frame.go
When a single active consumer with an offset is closed while no messages have been consumed, the offset 0 is sent to the server when closing the consumer gracefully and auto commit is enabled.
Recently `lastStoredOffset` was changed to be initialized with -1 for #306 , however that change caused this bug because the offset is only sent when `lastStoredOffset < currentOffset`. Because currentOffset is set to 0 by default by offset next and the default 0 initalization, `lastStoredOffset < currentOffset` is true when closing the consumer resulting in the offset 0 being sent. Because no messages were consumed either the offset was not populated.
=> fix offset of single active consumer reset to 0

examples/reliable/reliable_client.go, pkg/ha/ha_publisher.go, pkg/ha/ha_publisher_test.go
If there are parallel calls to `Send` or `BatchSend` in concurrent routines during reconnection, only one of these sends will unlock and send the message, while the others will remain in a locked state. This is because currently there isn't a broadcast notification with reconnectionSignal. 
To fix this issue the `reconnectionSigna`l channel has been changed to a `sync.Cond`.
=> Fix the reconnection logic for parallel writes with HA Producer.

pkg/stream/super_stream_producer_test.go
The test "should Send messages and confirm to all the streams" random fails on Windows.
This PR adds some logs to check what happens during the CI. 
I can't reproduce the problem locally
=> add logs to the failing test

pkg/stream/available_features.go, pkg/stream/client.go, pkg/stream/utils.go
Fixes: https://github.com/rabbitmq/rabbitmq-stream-go-client/issues/344 
When the `serverProperties["version"]` is not empty the client now checks the version. 
If the version is >=3.11 it is possible to enable the `exchangeVersion` function. 
Fixes another small bug when the [single active consumer is enabled](https://github.com/rabbitmq/rabbitmq-stream-go-client/pull/345/files#diff-4fb6ad931a13179f366870a7cc4500615ed0380fce0a7c6390f2e68bd553b24dL48) 
cc @hiimjako
=> Check version when version is not

pkg/stream/environment.go
Logging `client.broker` will also log the password used to connect to the server. Replaced it with safe URI
=> Removed the password log during reconnection

pkg/stream/client.go
The error is raised by staticcheck v0.5.1
See: https://github.com/rabbitmq/rabbitmq-stream-go-client/actions/runs/10457666416/job/28957811798#step:7:96
=>  staticcheck error

pkg/stream/client.go
and deletion when the broker is less 3.13.0
ref: https://github.com/rabbitmq/rabbitmq-stream-go-client/issues/354
=> check super stream creation

pkg/stream/brokers.go, pkg/stream/client.go, pkg/stream/constants.go, pkg/stream/environment.go, pkg/stream/environment_test.go, pkg/stream/producer.go
the configuration. In case a heartbeat less than 20 seconds the client could raise missing heart beat. In some case could disconnect the client
=> Adapt the heartbeat checker to the configuration.

examples/reliable/reliable_client.go, perfTest/cmd/commands.go, perfTest/cmd/silent.go, pkg/stream/aggregation.go, pkg/stream/aggregation_test.go, pkg/stream/coordinator.go, pkg/stream/producer.go, pkg/stream/producer_test.go, pkg/stream/server_frame.go, pkg/stream/super_stream_consumer_test.go, pkg/stream/super_stream_producer.go, pkg/stream/super_stream_producer_test.go
Part of https://github.com/rabbitmq/rabbitmq-stream-go-client/issues/365
- Change the lock type for unconfirmed messages. Use RWlock instead of Lock.
- Use the RLock when the map is read.
- Aggregate the messages and add unconfirmed messages in a batch way.
- Aggregate the messages and remove unconfirmed messages in a bach way.
- Pass point array of *messageSequence
This PR (using batch Send) 
----
```
2024/11/28 15:41:06 [info] - Published 1,212,812.8 msg/s | Confirmed 1,211,755.8 msg/s |  Consumed 1,213,207.2 msg/s |  Full | Body sz: 8 | latency: 7 ms
2024/11/28 15:41:07 [info] - Published 1,229,614.8 msg/s | Confirmed 1,221,792.4 msg/s |  Consumed 1,228,231.6 msg/s |  Full | Body sz: 8 | latency: 7 ms
2024/11/28 15:41:08 [info] - Published 1,218,139.4 msg/s | Confirmed 1,216,236.7 …
```
=> Improve batch send performances

.github/workflows/build_and_test.yml, README.md, pkg/amqp/types.go, pkg/ha/ha_consumer.go, pkg/stream/aggregation_test.go, pkg/stream/blocking_queue.go, pkg/stream/client.go, pkg/stream/constants.go, pkg/stream/consumer.go, pkg/stream/consumer_test.go, pkg/stream/coordinator.go, pkg/stream/coordinator_test.go, pkg/stream/environment.go, pkg/stream/environment_test.go, pkg/stream/listeners.go, pkg/stream/producer.go, pkg/stream/producer_test.go, pkg/stream/producer_unconfirmed.go, pkg/stream/server_frame.go
- Refactor the consumer to deal with some edge case whit the metadata update  
- Aggregate the confirmation responses to be faster during the unconfirmed extraction 
- refactor the message sequence struct to remove the reference to the original message ( it could increase the  memory usage in some case )
=> Consumer improvements for 1.5

Makefile, pkg/ha/ha_publisher.go, pkg/stream/blocking_queue.go, pkg/stream/constants.go, pkg/stream/producer.go, pkg/stream/producer_test.go, pkg/stream/producer_unconfirmed.go, pkg/stream/server_frame.go
This is a sub-branch of check_close_during_send, so please ensure that [PR #372](https://github.com/rabbitmq/rabbitmq-stream-go-client/pull/372) is merged first.
This PR introduces performance improvements by leveraging slice preallocation and reducing the average size of the unConfirmed map, which now only stores the currently in-flight messages.
Note: Additionally, I identified the root cause of the performance degradation observed in the client under high traffic or client reconnections in cloud environments. This issue appears to be related to [Issue #293](https://github.com/rabbitmq/rabbitmq-stream-go-client/issues/293) and is associated with the default TCP socket settings. I suspect this is OS-related, as it manifests on Linux (tested on an AWS cluster with ARM64 nodes running …
=> Performance improvement on unconfirmed map

best_practices/README.md, pkg/stream/client.go
Make possible to avoid the system call to update TCP parameters.
=> Set TCP parameters only if they are greater than 0

pkg/stream/producer_test.go
small pr to avoid data race in the publish error test
cc @hiimjako
=> wait metadata

perfTest/cmd/commands.go, pkg/stream/constants.go, pkg/stream/coordinator.go, pkg/stream/producer.go, pkg/stream/producer_test.go, pkg/stream/producer_unconfirmed.go, pkg/stream/server_frame.go
The producer is blocked when the limit is reached. It is possible to configure the limit using the producerOption.QueueSize setting.
Closes: https://github.com/rabbitmq/rabbitmq-stream-go-client/issues/373
Close the TCP client connection in case of CRC fail. The panic is removed. Closes: https://github.com/rabbitmq/rabbitmq-stream-go-client/issues/368
=> Add limit to the unconfirmed messages

pkg/ha/ha_consumer.go, pkg/stream/client.go, pkg/stream/constants.go, pkg/stream/consumer.go, pkg/stream/coordinator.go, pkg/stream/producer_unconfirmed.go
with a load balancer configuration the disconnection can take time due of heartbeat in this pr the client detects possible zombie consumers
=> Detect zombie consumer

pkg/integration_test/stream_integration_test.go, pkg/stream/client.go, pkg/stream/server_frame.go
Problem:
Sometimes the timestamp value can be written as an offset in rabbitmq, which freezes message consumption. 
**Real case**: You add a new consumer to an existing stream for which the offset is not yet set. You do not want to reread all messages, so you specify -1 min. If there are no messages for a certain time and automatic flush is triggered, this timestamp value will be written as the offset.
As a summary, based on the code in the library and the stream protocol, it looks like the method `consumer.setCurrentOffset` should only be called with a typeOffset value.
=> Fix handling and storing offset by timestamp

pkg/stream/client.go, pkg/stream/coordinator.go, pkg/stream/environment.go, pkg/stream/super_stream_producer_test.go
A potential **deadlock** issue was identified in the function when handling changes in stream metadata. This issue occurs when the stream members are updated (e.g., disabling or modifying replicas). The deadlock caused execution to hang indefinitely, leaving publisher disconnected
To reproduce the issue:
- A new test, **`should reconnect to the same partition after a close event`**, was introduced.
- The test successfully replicates the failure by simulating metadata updates and validating the ability of producers to reconnect to a specific partition after a clean-up operation.
- **When did it happen?**
- This issue was triggered when stream metadata was changed, such as updates to stream replicas.
- **How did the application behave?**
- The application ran without restrictions with …
=> Fix producers reconnection deadlock

pkg/stream/client_test.go, pkg/stream/coordinator.go, pkg/stream/server_frame.go
Fix Panic on Response Timeout in `handleWriteWithResponse`
When it happened: 
1. You declare a publisher, but for some reason, the response from the RabbitMQ is delayed
2. [handleWriteWithResponse](https://github.com/rabbitmq/rabbitmq-stream-go-client/blob/main/pkg/stream/socket.go#L68) handle timeout and remove response from coordinator
3. Delayed response arrived from Rabbitmq into [handleGenericResponse](https://github.com/rabbitmq/rabbitmq-stream-go-client/blob/main/pkg/stream/server_frame.go#L209), but GetResponseById can't find the response because it was deleted in step 2, and we got a panic
=> Fix panic when response failed by timeout

pkg/ha/ha_consumer.go, pkg/ha/ha_publisher.go, pkg/ha/reliable_common.go
Makes the `GetStreamName()` method public for HA clients to align with the standard consumer and producer APIs, where it is already exposed.
=> Expose GetStreamName in HA Client

pkg/stream/consumer.go, pkg/stream/consumer_test.go, pkg/stream/server_frame.go
Tested and fixed the issue described in #393.
Added a drain with @Gsantomaggio before the close to avoid race condition with the client with pending messages.
More details are also in this PR #411.
=> Avoid to panic on close when the consumer internal queue is full

pkg/stream/client.go, pkg/stream/consumer_test.go, pkg/stream/coordinator.go, pkg/stream/server_frame.go
This PR moves the `AutomaticCreditStrategy` into the handler thread. It now requests credits after half of a chunk has been processed, which aligns its behavior with the Java client.
This change prevents the main socket loop from blocking and ensures that heartbeats are handled correctly.
Fixes #439 
Performance remains quite the same. The following command was used for testing, with 15 samples recorded for each run:
`go run ./perftest.go --publishers 1 --consumers 1 --streams test-stream --max-length-bytes 2GB --initial-credits <num>`
- Default credits (10):
- main
```sh
2026/09/25 18:55:38 [info] - Silent (1.6.0) Simulation, url: [rabbitmq-stream://guest:guest@localhost:5552/%2f] publishers: 1 consumers: 1 streams: [my_stream_curr] 
2025/09/25 18:55:38 [info] - Declaring streams: …
```
=> Move automatic credit strategy in the handler thread
